server:
  port: 8889

spring:
  rabbitmq:
    host: 123.56.97.130
    port: 5672
    username: shenyao
    password: 123456
    virtual-host: /
    publisher-confirms: true
    publisher-returns: true
    listener:
      direct:
        acknowledge-mode: MANUAL
      simple:
        prefetch: 1
        acknowledge-mode: manual
        retry:
          enabled: true

