server:
  port: 8889

spring:
  rabbitmq:
    host: 47.97.192.128
    port: 5672
    username: shenyao
    password: 123456
    virtual-host: /test
    publisher-confirms: true
    publisher-returns: true
    listener:
      direct:
        acknowledge-mode: MANUAL
      simple:
        acknowledge-mode: manual
        retry:
          enabled: true
