server:
  port: 90

spring:
  rabbitmq:
    host: 123.56.97.130
    port: 5672
    username: shenyao
    password: 123456
    virtual-host: /
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true

  #当遇到同样名字的时候，是否允许覆盖注册
  main:
    allow-bean-definition-overriding: true

